import type { ItemDefinition } from './types';

export const itemsRegistry: Record<string, ItemDefinition> = {
  // --- SWORDS ---
  sword_common: {
    id: 'sword_common',
    name: 'Espada Velha',
    description: 'Uma espada cega e pesada.',
    category: 'weapon',
    family: 'sword',
    rarity: 'common',
    icon: '🗡️',
    baseDamage: 10,
    passiveName: 'Corte Simples',
    passiveDescription: 'Combo leve.',
    activeName: 'Golpe Pesado',
    activeDescription: 'Dano básico de impacto.',
    activeManaCost: 10,
  },
  sword_rare: {
    id: 'sword_rare',
    name: 'Espada de Aço',
    description: 'Forjada para combate real.',
    category: 'weapon',
    family: 'sword',
    rarity: 'rare',
    icon: '⚔️',
    baseDamage: 25,
    passiveName: 'Combo Eficiente',
    passiveDescription: 'Bônus de dano em combos.',
    activeName: 'Lâmina Cruzada',
    activeDescription: 'Dano médio ampliado.',
    activeManaCost: 15,
  },
  sword_epic: {
    id: 'sword_epic',
    name: 'Espada do Cavaleiro',
    description: 'Uma arma de elite decorada com ouro.',
    category: 'weapon',
    family: 'sword',
    rarity: 'epic',
    icon: '⚜️',
    baseDamage: 45,
    passiveName: 'Sequência Imperial',
    passiveDescription: 'Bônus significativo em combos.',
    activeName: 'Julgamento Reto',
    activeDescription: 'Dano alto ampliado.',
    activeManaCost: 20,
  },
  sword_legendary: {
    id: 'sword_legendary',
    name: 'Espada Lendária',
    description: 'Uma arma mitológica imbuída de poder.',
    category: 'weapon',
    family: 'sword',
    rarity: 'legendary',
    icon: '✨',
    baseDamage: 75,
    passiveName: 'Corte do Destino',
    passiveDescription: 'Chance de crítico e bônus de combo massivo.',
    activeName: 'Fúria dos Deuses',
    activeDescription: 'Dano explosivo e efeito especial.',
    activeManaCost: 25,
  },

  // --- KATANAS ---
  katana_common: {
    id: 'katana_common',
    name: 'Katana Enferrujada',
    description: 'Desgastada, mas ainda rápida.',
    category: 'weapon',
    family: 'katana',
    rarity: 'common',
    icon: '🔪',
    baseDamage: 12,
    passiveName: 'Fio Cego',
    passiveDescription: 'Pequena chance crítica.',
    activeName: 'Corte Rápido',
    activeDescription: 'Dano veloz.',
    activeManaCost: 12,
  },
  katana_rare: {
    id: 'katana_rare',
    name: 'Katana Afiada',
    description: 'Corta o ar com precisão.',
    category: 'weapon',
    family: 'katana',
    rarity: 'rare',
    icon: '🤺',
    baseDamage: 28,
    passiveName: 'Fio de Navalha',
    passiveDescription: 'Chance crítica aumentada.',
    activeName: 'Andar do Vento',
    activeDescription: 'Ignora penalidades temporárias.',
    activeManaCost: 18,
  },
  katana_epic: {
    id: 'katana_epic',
    name: 'Katana do Mestre',
    description: 'A lâmina perfeita de um samurai lendário.',
    category: 'weapon',
    family: 'katana',
    rarity: 'epic',
    icon: '👺',
    baseDamage: 50,
    passiveName: 'Disciplina Marcial',
    passiveDescription: 'Alta chance crítica.',
    activeName: 'Lâmina de Sangue',
    activeDescription: 'Ataca múltiplas vezes.',
    activeManaCost: 22,
  },
  katana_legendary: {
    id: 'katana_legendary',
    name: 'Katana Suprema',
    description: 'Corta o próprio tecido da realidade.',
    category: 'weapon',
    family: 'katana',
    rarity: 'legendary',
    icon: '🐉',
    baseDamage: 85,
    passiveName: 'Corte do Vazio',
    passiveDescription: 'Chance crítica máxima.',
    activeName: 'Técnica Proibida',
    activeDescription: 'Aniquilação total.',
    activeManaCost: 30,
  },

  // --- DAGGERS ---
  dagger_common: {
    id: 'dagger_common',
    name: 'Adaga Simples',
    description: 'Uma faca de cozinha usada em combate.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'common',
    icon: '🍴',
    baseDamage: 8,
    passiveName: 'Leveza',
    passiveDescription: 'Velocidade de resposta.',
    activeName: 'Golpe Baixo',
    activeDescription: 'Dano rápido.',
    activeManaCost: 8,
  },
  dagger_rare: {
    id: 'dagger_rare',
    name: 'Adaga Balanceada',
    description: 'Perfeita para lançamentos rápidos.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'rare',
    icon: '🏹',
    baseDamage: 22,
    passiveName: 'Equilíbrio',
    passiveDescription: 'Reduz alternativas erradas.',
    activeName: 'Venenosa',
    activeDescription: 'Dano por tempo.',
    activeManaCost: 12,
  },
  dagger_epic: {
    id: 'dagger_epic',
    name: 'Adaga Sombria',
    description: 'Feita de obsidiana, brilha no escuro.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'epic',
    icon: '🌑',
    baseDamage: 40,
    passiveName: 'Invisibilidade',
    passiveDescription: 'Grande redução de alternativas.',
    activeName: 'Assassinar',
    activeDescription: 'Dano crítico garantido.',
    activeManaCost: 18,
  },
  dagger_legendary: {
    id: 'dagger_legendary',
    name: 'Adaga Fantasma',
    description: 'Não pertence a este mundo.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'legendary',
    icon: '👻',
    baseDamage: 70,
    passiveName: 'Presença Espectral',
    passiveDescription: 'Apenas 2 alternativas por questão.',
    activeName: 'Golpe do Além',
    activeDescription: 'Dano massivo imparável.',
    activeManaCost: 25,
  },

  // --- BOWS ---
  bow_common: {
    id: 'bow_common',
    name: 'Arco Curto',
    description: 'Feito de madeira flexível.',
    category: 'weapon',
    family: 'bow',
    rarity: 'common',
    icon: '🏹',
    baseDamage: 11,
    passiveName: 'Precisão',
    passiveDescription: 'Bônus por tempo rápido.',
    activeName: 'Flecha Dupla',
    activeDescription: 'Dano duplo.',
    activeManaCost: 10,
  },
  bow_rare: {
    id: 'bow_rare',
    name: 'Arco Reforçado',
    description: 'Composto de madeira e osso.',
    category: 'weapon',
    family: 'bow',
    rarity: 'rare',
    icon: '🏹',
    baseDamage: 26,
    passiveName: 'Olho de Águia',
    passiveDescription: 'Bônus por tempo aumentado.',
    activeName: 'Chuva de Flechas',
    activeDescription: 'Dano em área.',
    activeManaCost: 16,
  },
  bow_epic: {
    id: 'bow_epic',
    name: 'Arco de Elite',
    description: 'Usado pelos melhores arqueiros do reino.',
    category: 'weapon',
    family: 'bow',
    rarity: 'epic',
    icon: '🏹',
    baseDamage: 48,
    passiveName: 'Sniper',
    passiveDescription: 'Grande bônus por rapidez.',
    activeName: 'Flecha Perfurante',
    activeDescription: 'Atravessa defesas.',
    activeManaCost: 20,
  },
  bow_legendary: {
    id: 'bow_legendary',
    name: 'Arco Lendário',
    description: 'Suas flechas são feitas de luz pura.',
    category: 'weapon',
    family: 'bow',
    rarity: 'legendary',
    icon: '🏹',
    baseDamage: 80,
    passiveName: 'Mestre Arqueiro',
    passiveDescription: 'Bônus máximo por tempo de resposta.',
    activeName: 'Estrela Cadente',
    activeDescription: 'Impacto celestial.',
    activeManaCost: 30,
  },

  // --- AXES ---
  axe_common: {
    id: 'axe_common',
    name: 'Machado Gasto',
    description: 'Usado para cortar lenha antes das guerras.',
    category: 'weapon',
    family: 'axe',
    rarity: 'common',
    icon: '🪓',
    baseDamage: 15,
    passiveName: 'Brutalidade',
    passiveDescription: 'Dano alto mas lento.',
    activeName: 'Giro',
    activeDescription: 'Dano pesado.',
    activeManaCost: 15,
  },
  axe_rare: {
    id: 'axe_rare',
    name: 'Machado de Guerra',
    description: 'Uma lâmina larga e pesada.',
    category: 'weapon',
    family: 'axe',
    rarity: 'rare',
    icon: '🪓',
    baseDamage: 32,
    passiveName: 'Fúria',
    passiveDescription: 'Dano amplificado por acertos.',
    activeName: 'Impacto Brutal',
    activeDescription: 'Dano massivo.',
    activeManaCost: 20,
  },
  axe_epic: {
    id: 'axe_epic',
    name: 'Machado Brutal',
    description: 'Manchado com as batalhas do passado.',
    category: 'weapon',
    family: 'axe',
    rarity: 'epic',
    icon: '🪓',
    baseDamage: 55,
    passiveName: 'Destruição',
    passiveDescription: 'Bônus de dano massivo.',
    activeName: 'Quebra-Solo',
    activeDescription: 'Dano de terremoto.',
    activeManaCost: 25,
  },
  axe_legendary: {
    id: 'axe_legendary',
    name: 'Machado do Titã',
    description: 'Pertenceu a um gigante primordial.',
    category: 'weapon',
    family: 'axe',
    rarity: 'legendary',
    icon: '🪓',
    baseDamage: 90,
    passiveName: 'Poder Titânico',
    passiveDescription: 'Dano absoluto em acertos.',
    activeName: 'Fim dos Tempos',
    activeDescription: 'Explosão cataclísmica.',
    activeManaCost: 40,
  },

  // --- ARMORS ---
  armor_light_common: {
    id: 'armor_light_common',
    name: 'Túnica Simples',
    description: 'Roupa comum de aventureiro.',
    category: 'armor',
    rarity: 'common',
    icon: '👕',
    defense: 5,
  },
  armor_heavy_rare: {
    id: 'armor_heavy_rare',
    name: 'Armadura de Ferro',
    description: 'Pesada, mas segura.',
    category: 'armor',
    rarity: 'rare',
    icon: '🛡️',
    defense: 15,
  },

  // --- ACCESSORIES ---
  acc_ring_mana: {
    id: 'acc_ring_mana',
    name: 'Anel de Mana',
    description: 'Aumenta a regeneração de Mana.',
    category: 'accessory',
    rarity: 'rare',
    icon: '💍',
  },

  // --- CONSUMABLES ---
  potion_health_small: {
    id: 'potion_health_small',
    name: 'Poção de Vida Menor',
    description: 'Recupera 25 HP.',
    category: 'consumable',
    rarity: 'common',
    icon: '❤️',
    effectType: 'heal',
    effectValue: 25,
  },
  potion_mana_small: {
    id: 'potion_mana_small',
    name: 'Frasco de Mana',
    description: 'Restaura 15 Mana.',
    category: 'consumable',
    rarity: 'uncommon',
    icon: '🧪',
    effectType: 'mana',
    effectValue: 15,
  },
  shield_consumable: {
    id: 'shield_consumable',
    name: 'Escudo Protetor',
    description: 'Bloqueia o próximo erro.',
    category: 'consumable',
    rarity: 'rare',
    icon: '🛡️',
    effectType: 'buff', // Special handling in reducer
    effectValue: 1,
  },
};
