import type { ItemDefinition } from './types';

export const itemsRegistry: Record<string, ItemDefinition> = {
  // --- SWORDS (Balanced/Combo) ---
  sword_common: {
    id: 'sword_common',
    name: 'Espada de Treino',
    description: 'Uma lâmina básica para iniciantes.',
    category: 'weapon',
    family: 'sword',
    rarity: 'common',
    icon: 'assets/game-images/Beautiful Blue Diamond Knife.png',
    baseDamage: 12,
    passiveName: 'Corte Constante',
    passiveDescription: 'Dano base sólido.',
    activeName: 'Golpe Direto',
    activeDescription: 'Impacto rápido.',
    activeManaCost: 15, // Low
  },
  sword_rare: {
    id: 'sword_rare',
    name: 'Glaive de Aço',
    description: 'Equilibrada para combate prolongado.',
    category: 'weapon',
    family: 'sword',
    rarity: 'rare',
    icon: '⚔️',
    baseDamage: 28,
    passiveName: 'Ritmo de Batalha',
    passiveDescription: 'Aumenta dano a cada combo.',
    activeName: 'Lâmina Giratória',
    activeDescription: 'Dano circular moderado.',
    activeManaCost: 35, // Mid
  },
  sword_epic: {
    id: 'sword_epic',
    name: 'Excalibur Menor',
    description: 'Uma réplica poderosa de uma lenda.',
    category: 'weapon',
    family: 'sword',
    rarity: 'epic',
    icon: '⚜️',
    baseDamage: 52,
    passiveName: 'Vontade Real',
    passiveDescription: 'Ganha mana extra em combos altos.',
    activeName: 'Corte Sagrado',
    activeDescription: 'Dano massivo e restaura 10 HP.',
    activeManaCost: 65, // High
  },
  sword_legendary: {
    id: 'sword_legendary',
    name: 'Lâmina do Infinito',
    description: 'Forjada no coração de uma estrela.',
    category: 'weapon',
    family: 'sword',
    rarity: 'legendary',
    icon: '✨',
    baseDamage: 85,
    passiveName: 'Unidade Cósmica',
    passiveDescription: 'Todo acerto após combo 3 é crítico.',
    activeName: 'Supernova',
    activeDescription: 'Dano explosivo total.',
    activeManaCost: 85, // Very High
  },

  // --- KATANAS (Crit/Speed/Burst) ---
  katana_common: {
    id: 'katana_common',
    name: 'Bokken de Carvalho',
    description: 'Treinamento de samurai.',
    category: 'weapon',
    family: 'katana',
    rarity: 'common',
    icon: '🔪',
    baseDamage: 14,
    passiveName: 'Foco Agudo',
    passiveDescription: 'Pequena chance de crítico (15%).',
    activeName: 'Estocada',
    activeDescription: 'Dano rápido de baixo custo.',
    activeManaCost: 20,
  },
  katana_rare: {
    id: 'katana_rare',
    name: 'Katana de Sakura',
    description: 'Pétalas caem a cada corte.',
    category: 'weapon',
    family: 'katana',
    rarity: 'rare',
    icon: '🌸',
    baseDamage: 32,
    passiveName: 'Dança das Flores',
    passiveDescription: 'Chance crítica aumentada (25%).',
    activeName: 'Corte de Vento',
    activeDescription: 'Dano cortante preciso.',
    activeManaCost: 40,
  },
  katana_epic: {
    id: 'katana_epic',
    name: 'Muramasa Sombria',
    description: 'Dizem que a lâmina tem sede de sangue.',
    category: 'weapon',
    family: 'katana',
    rarity: 'epic',
    icon: '👺',
    baseDamage: 58,
    passiveName: 'Sede de Sangue',
    passiveDescription: 'Altíssimo crítico (40%).',
    activeName: 'Mil Cortes',
    activeDescription: 'Série de ataques devastadores.',
    activeManaCost: 60,
  },
  katana_legendary: {
    id: 'katana_legendary',
    name: 'Kusanagi No Tsurugi',
    description: 'A lendária ceifadora de nuvens.',
    category: 'weapon',
    family: 'katana',
    rarity: 'legendary',
    icon: '🐉',
    baseDamage: 95,
    passiveName: 'Espírito do Dragão',
    passiveDescription: 'Crítico causa 3x de dano.',
    activeName: 'Iaijutsu Supremo',
    activeDescription: 'Ataque instantâneo imparável.',
    activeManaCost: 90,
  },

  // --- AXES (Raw Power/Brutality) ---
  axe_common: {
    id: 'axe_common',
    name: 'Machado de Lenhador',
    description: 'Simples e funcional.',
    category: 'weapon',
    family: 'axe',
    rarity: 'common',
    icon: '🪓',
    baseDamage: 18,
    passiveName: 'Peso Morto',
    passiveDescription: 'Dano elevado, mas sem crits.',
    activeName: 'Machadada',
    activeDescription: 'Impacto bruto.',
    activeManaCost: 25,
  },
  axe_rare: {
    id: 'axe_rare',
    name: 'Machado de Guerra Bárbaro',
    description: 'Terror dos campos de batalha.',
    category: 'weapon',
    family: 'axe',
    rarity: 'rare',
    icon: '⚒️',
    baseDamage: 38,
    passiveName: 'Fúria Incontrolável',
    passiveDescription: 'Ganha dano ao perder HP.',
    activeName: 'Redemoinho',
    activeDescription: 'Giro devastador.',
    activeManaCost: 45,
  },
  axe_epic: {
    id: 'axe_epic',
    name: 'Quebra-Crânios',
    description: 'Uma arma de puro terror.',
    category: 'weapon',
    family: 'axe',
    rarity: 'epic',
    icon: 'assets/game-images/Beautiful Blue Diamond Knife.png',
    baseDamage: 65,
    passiveName: 'Esmagar Ossos',
    passiveDescription: 'Chance de dano crítico massivo (10% para 2.5x).',
    activeName: 'Terremoto',
    activeDescription: 'Dano de área gigante.',
    activeManaCost: 70,
  },
  axe_legendary: {
    id: 'axe_legendary',
    name: 'Labrys do Caos',
    description: 'O machado que dividiu o mundo.',
    category: 'weapon',
    family: 'axe',
    rarity: 'legendary',
    icon: '🌀',
    baseDamage: 110,
    passiveName: 'Fim de Tudo',
    passiveDescription: 'Dano massivo imparável.',
    activeName: 'Cataclismo',
    activeDescription: 'Dano terminal absoluto.',
    activeManaCost: 95,
  },

  // --- DAGGERS (Utility/Speed) ---
  dagger_common: {
    id: 'dagger_common',
    name: 'Faca de Bronze',
    description: 'Pequena e discreta.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'common',
    icon: '🍴',
    baseDamage: 10,
    passiveName: 'Golpe Rápido',
    passiveDescription: 'Chance de hit duplo.',
    activeName: 'Punhalada',
    activeDescription: 'Ataque furtivo.',
    activeManaCost: 10,
  },
  dagger_rare: {
    id: 'dagger_rare',
    name: 'Estilete de Assassino',
    description: 'Projetada para pontos vitais.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'rare',
    icon: 'assets/game-images/Beautiful Blue Diamond Knife.png',
    baseDamage: 25,
    passiveName: 'Ponto Fraco',
    passiveDescription: 'Ignora parte da defesa.',
    activeName: 'Veneno Letal',
    activeDescription: 'Dano por tempo elevado.',
    activeManaCost: 30,
  },
  dagger_epic: {
    id: 'dagger_epic',
    name: 'Adaga de Sombras',
    description: 'A lâmina desaparece na luz.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'epic',
    icon: '🌑',
    baseDamage: 45,
    passiveName: 'Passo das Sombras',
    passiveDescription: 'Restaura 5 mana por acerto.',
    activeName: 'Execução',
    activeDescription: 'Dano triplicado se Mana > 50.',
    activeManaCost: 50,
  },
  dagger_legendary: {
    id: 'dagger_legendary',
    name: 'Lâminas Gêmeas do Destino',
    description: 'Uma em cada mão, o dobro de perigo.',
    category: 'weapon',
    family: 'dagger',
    rarity: 'legendary',
    icon: '✨',
    baseDamage: 75,
    passiveName: 'Dualidade',
    passiveDescription: 'Ganha mana e vida por acerto.',
    activeName: 'Valsa da Morte',
    activeDescription: 'Dano contínuo imparável.',
    activeManaCost: 75,
  },

  // --- BOWS (Timed/Strategic) ---
  bow_common: {
    id: 'bow_common',
    name: 'Arco de Caça',
    description: 'Usado para caça menor.',
    category: 'weapon',
    family: 'bow',
    rarity: 'common',
    icon: '🏹',
    baseDamage: 12,
    passiveName: 'Foco no Alvo',
    passiveDescription: 'Dano bônus por rapidez.',
    activeName: 'Tiro Certeiro',
    activeDescription: 'Dano à distância.',
    activeManaCost: 15,
  },
  bow_rare: {
    id: 'bow_rare',
    name: 'Arco Longo de Carvalho',
    description: 'Grande alcance e poder.',
    category: 'weapon',
    family: 'bow',
    rarity: 'rare',
    icon: '🏹',
    baseDamage: 28,
    passiveName: 'Olho de Falcão',
    passiveDescription: 'Bônus de tempo ampliado.',
    activeName: 'Chuva de Setas',
    activeDescription: 'Dano em área moderado.',
    activeManaCost: 40,
  },
  bow_epic: {
    id: 'bow_epic',
    name: 'Arco de Cristal',
    description: 'Flechas de energia pura.',
    category: 'weapon',
    family: 'bow',
    rarity: 'epic',
    icon: '💎',
    baseDamage: 55,
    passiveName: 'Resonância',
    passiveDescription: 'Ganha mana por respostas rápidas.',
    activeName: 'Flecha de Luz',
    activeDescription: 'Dano alto perfurante.',
    activeManaCost: 55,
  },
  bow_legendary: {
    id: 'bow_legendary',
    name: 'Arco das Constelações',
    description: 'Atira estrelas cadentes.',
    category: 'weapon',
    family: 'bow',
    rarity: 'legendary',
    icon: '🌌',
    baseDamage: 90,
    passiveName: 'Zodíaco',
    passiveDescription: 'Dano massivo baseado no tempo.',
    activeName: 'Chuva Estelar',
    activeDescription: 'Bombardeio celestial total.',
    activeManaCost: 80,
  },

  // --- ARMORS (Defense) ---
  armor_light_common: {
    id: 'armor_light_common',
    name: 'Túnica de Linho',
    description: 'Leve e flexível.',
    category: 'armor',
    rarity: 'common',
    icon: 'assets/game-images/keinianz-helmet-5724641_1920.jpg',
    defense: 5,
  },
  armor_light_rare: {
    id: 'armor_light_rare',
    name: 'Colete de Couro Batido',
    description: 'Proteção básica reforçada.',
    category: 'armor',
    rarity: 'rare',
    icon: '🧥',
    defense: 12,
  },
  armor_heavy_rare: {
    id: 'armor_heavy_rare',
    name: 'Cota de Malha',
    description: 'Resistente a cortes.',
    category: 'armor',
    rarity: 'rare',
    icon: '⛓️',
    defense: 18,
  },
  armor_heavy_epic: {
    id: 'armor_heavy_epic',
    name: 'Placa de Aço Real',
    description: 'Armadura digna de um general.',
    category: 'armor',
    rarity: 'epic',
    icon: '🛡️',
    defense: 35,
  },
  armor_legendary: {
    id: 'armor_legendary',
    name: 'Armadura de Adamantio',
    description: 'Indestrutível.',
    category: 'armor',
    rarity: 'legendary',
    icon: '💎',
    defense: 60,
  },

  // --- ACCESSORIES (Buffs) ---
  acc_ring_mana: {
    id: 'acc_ring_mana',
    name: 'Anel de Safira',
    description: 'Aumenta ganhos de Mana em 20%.',
    category: 'accessory',
    rarity: 'rare',
    icon: '💍',
  },
  acc_pendant_crit: {
    id: 'acc_pendant_crit',
    name: 'Pingente do Destino',
    description: 'Aumenta chance crítica em 10%.',
    category: 'accessory',
    rarity: 'epic',
    icon: '📿',
  },

  // --- CONSUMABLES ---
  potion_health_small: {
    id: 'potion_health_small',
    name: 'Poção de Vida',
    description: 'Recupera 25 HP.',
    category: 'consumable',
    rarity: 'common',
    icon: 'assets/game-images/vial of health potion.png',
    effectType: 'heal',
    effectValue: 25,
  },
  potion_health_large: {
    id: 'potion_health_large',
    name: 'Elixir de Vitalidade',
    description: 'Recupera 60 HP.',
    category: 'consumable',
    rarity: 'rare',
    icon: 'assets/game-images/pikura-cakes-9126300_1920.png',
    effectType: 'heal',
    effectValue: 60,
  },
  potion_mana_small: {
    id: 'potion_mana_small',
    name: 'Frasco de Mana',
    description: 'Restaura 20 Mana.',
    category: 'consumable',
    rarity: 'uncommon',
    icon: '💎',
    effectType: 'mana',
    effectValue: 20,
  },
  potion_mana_large: {
    id: 'potion_mana_large',
    name: 'Cristal de Mana Puro',
    description: 'Restaura 50 Mana.',
    category: 'consumable',
    rarity: 'epic',
    icon: '🔮',
    effectType: 'mana',
    effectValue: 50,
  },
  shield_consumable: {
    id: 'shield_consumable',
    name: 'Orbe de Proteção',
    description: 'Absorve 20 de dano do próximo erro.',
    category: 'consumable',
    rarity: 'rare',
    icon: '🛡️',
    effectType: 'buff',
    effectValue: 20,
  },
  armor_helmet: {
    id: 'armor_helmet',
    name: 'Elmo de Batalha',
    description: 'Proteção pesada para a cabeça.',
    category: 'armor',
    rarity: 'rare',
    icon: 'assets/game-images/keinianz-helmet-5724641_1920.jpg',
    defense: 15,
  },
  item_turkey_leg: {
    id: 'item_turkey_leg',
    name: 'Coxa de Peru',
    description: 'Um banquete real! Recupera 35 HP.',
    category: 'consumable',
    rarity: 'rare',
    icon: 'assets/game-images/havingfunandsharing-leg-9181658_1920.png',
    effectType: 'heal',
    effectValue: 35,
  },

  // --- NEW ITEMS ---
  item_beer: {
    id: 'item_beer',
    name: 'Cerveja de Cevada',
    description: 'Restaura 30 de Mana. Cuidado com o exagero!',
    category: 'consumable',
    rarity: 'uncommon',
    icon: 'assets/game-images/lesiakower-beer-7370681_1920.png',
    effectType: 'mana',
    effectValue: 30,
  },
  item_red_fruit: {
    id: 'item_red_fruit',
    name: 'Fruta Vermelha',
    description: 'Recupera 15 HP. Fresca e suculenta.',
    category: 'consumable',
    rarity: 'common',
    icon: 'assets/game-images/divexfre-red-fruit-9741345_1920.png',
    effectType: 'heal',
    effectValue: 15,
  },
  item_pastry: {
    id: 'item_pastry',
    name: 'Pastel Psicodélico',
    description: 'Restaura 20 HP e 15 Mana.',
    category: 'consumable',
    rarity: 'rare',
    icon: 'assets/game-images/appetizing psychedelic pastry.png',
    effectType: 'heal', // Will need special handling in reducer for dual effect
    effectValue: 20,
  },
  item_bag_gold: {
    id: 'item_bag_gold',
    name: 'Saco de Ouro',
    description: 'Restaura 50 Mana instantaneamente.',
    category: 'consumable',
    rarity: 'epic',
    icon: 'assets/game-images/bag of gold.png',
    effectType: 'mana',
    effectValue: 50,
  },
};
